class TypeError(Exception): ...
class LengthError(Exception): ...
class IndexError(Exception): ...
class FunctionError(Exception): ...
class ColorError(Exception): ...
class FontError(Exception): ...
class ValueError(Exception): ...